language: python
python:
  - "3.6"
before_install:
  - pip install flake8
  - flake8 validator/
  - pip install coverage
  - pip install nltk
  - python -m nltk.downloader snowball_data words stopwords punkt
script:
  - coverage run -m pytest
after_success:
  # Report test coverage
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
